version: "3.9"
services:
  db:
    container_name: notification_db
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: "notification_db"
      POSTGRES_USER: "developer"
      POSTGRES_PASSWORD: "parol"
    ports:
      - "5432:5432"
